<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260623073018 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Baseline schema: employee, leave_balance and leave_request. The Messenger transport table is managed by Messenger itself.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE employee (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(255) NOT NULL,
              employment_start_date DATE NOT NULL,
              working_days_per_week INT NOT NULL,
              federal_state VARCHAR(2) NOT NULL,
              contractual_leave_days INT NOT NULL,
              employment_end_date DATE DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE leave_balance (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              year INT NOT NULL,
              carried_over_days DOUBLE PRECISION NOT NULL,
              carryover_expires_on DATE DEFAULT NULL,
              used_days DOUBLE PRECISION NOT NULL,
              employee_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_EAAB67198C03F15C ON leave_balance (employee_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_employee_year ON leave_balance (employee_id, year)');
        $this->addSql(<<<'SQL'
            CREATE TABLE leave_request (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              status VARCHAR(255) NOT NULL,
              half_day_start BOOLEAN NOT NULL,
              half_day_end BOOLEAN NOT NULL,
              medical_certificate BOOLEAN NOT NULL,
              decided_at DATE DEFAULT NULL,
              decision_reason VARCHAR(255) DEFAULT NULL,
              external_reference VARCHAR(255) DEFAULT NULL,
              type VARCHAR(255) NOT NULL,
              start_date DATE NOT NULL,
              end_date DATE NOT NULL,
              submitted_at DATE NOT NULL,
              employee_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_7DC8F7788C03F15C ON leave_request (employee_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              leave_balance
            ADD
              CONSTRAINT FK_EAAB67198C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              leave_request
            ADD
              CONSTRAINT FK_7DC8F7788C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE leave_balance DROP CONSTRAINT FK_EAAB67198C03F15C');
        $this->addSql('ALTER TABLE leave_request DROP CONSTRAINT FK_7DC8F7788C03F15C');
        $this->addSql('DROP TABLE employee');
        $this->addSql('DROP TABLE leave_balance');
        $this->addSql('DROP TABLE leave_request');
    }
}
